NXDK_DIR = $(CURDIR)/../../nxdk

DXT_TITLE = CheatX

SRCS = main.c \
	XbSymbolDatabase/XbSymbolDatabase.c \
	memfuncs.c \
	searchfuncs.c \
	inputhook.c \
	txtcodes.c

DEBUG = n

include $(NXDK_DIR)/Makefile_dxt
